version: '3.8'

services:
  db:
    image: postgres:15
    platform: linux/arm64
    container_name: WAD
    environment:
      POSTGRES_PASSWORD: wad
      POSTGRES_USER: wad
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
