server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=wad
spring.datasource.password=wad
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=wad-lab5-super-secret-key-that-is-long-enough-for-hs256
jwt.expiration=86400000